USE master
GO

CREATE DATABASE DB_TRANSACTION
GO

USE DB_TRANSACTION
GO

CREATE TABLE TRANSACTIONS(
	ID INT IDENTITY(1,1) NOT NULL,
	TYPE VARCHAR(8) NOT NULL,
	AMOUNT DECIMAL(19,2) NOT NULL,
	DATE DATETIME DEFAULT GETDATE(),
	DESCRIPTION VARCHAR(255) NOT NULL,
	CATEGORY VARCHAR(30) NOT NULL,
	BALANCE DECIMAL DEFAULT 0,
	CONSTRAINT PK_TRANSACTIONS PRIMARY KEY(ID)
);